### ISSUE TITLE
Alfa Romeo Giulia

### ISSUE THREAD

**Issue by gaucho1978** [iDoka/awesome-automotive-can-id#9]
No decoding for Giulia?

**Comment by iDoka** [comment]
AFAIK, at this moment no one shared/reverse-engineered Alfa Romeo models.

**Comment by fyrak1s** [comment]
This guy has decoded a bunch if I understand correctly: https://medium.com/@fmntf/fiat-infotainment-can-messages-67591a22ed2f
repo: https://github.com/fmntf/fiatcan
